openapi: 3.0.0
info:
  title: Task Planner API
  contact: {}
  version: '0.1.0'
host: 'http://localhost:3000'
basePath: '/api/v1'
schemes:
- 'https'
- 'http'
servers:
  - url: 'http://localhost:3000'
    variables: {}
paths:
  /api/v1/tasks:
    post:
      tags:
        - 'tasks'
      summary: Create Task
      operationId: createTask
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              type: object
              properties:
                title: 
                  type: string
                completed: 
                  type: boolean
            example:
              title: research topic
              completed: false
        required: true
      responses:
        '200':
          description: 'successful operation'
          headers: {}
      deprecated: false
    get:
      tags:
        - 'tasks'
      summary: Get All Tasks
      operationId: getAllTasks
      parameters: []
      responses:
        '200':
          description: 'successful operation'
          headers: {}
      deprecated: false
  /api/v1/tasks/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: 'string'
        required: true
        description: The task ID
    get:
      tags:
        - 'tasks'
      summary: Get Single Task
      operationId: getSingleTask
      parameters: []
      responses:
        '200':
          description: 'successful operation'
          headers: {}
      deprecated: false

    patch:
      tags:
        - 'tasks'
      summary: Update Task
      operationId: updateTask
      parameters: []
      requestBody:
        description: ''
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTaskRequest'
            example:
              company: random
              position: intern
        required: true
      responses:
        '200':
          description: 'successful operation'
          headers: {}
      deprecated: false
    delete:
      tags:
        - 'tasks'
      summary: Delete Task
      operationId: deleteTask
      parameters: []
      responses:
        '200':
          description: 'successful operation'
          headers: {}
      deprecated: false
components:
  schemas:
    CreateTaskRequest:
      title: CreateTaskRequest
      required:
        - title
        - completed
      type: object
      properties:
        title:
          type: 'string'
        completed:
          type: 'boolean'
      example:
        title: design
        completed: false
    UpdateJobRequest:
      title: UpdateTaskRequest
      required:
        - title
        - completed
      type: object
      properties:
        title:
          type: 'string'
        completed:
          type: 'boolean'
      example:
        title: test
        completed: false
  securitySchemes:
    httpBearer:
      type: http
      scheme: bearer
security:
  - httpBearer: []
tags:
  - name: tasks
    description: ''